export default {
  APP_READY: 'APP_READY',
  SHOW_NAVBAR: 'SHOW_NAVBAR',
  SHOW_INTRO_BOXES: 'SHOW_INTRO_BOXES',
  SHOW_INTRO_CONTENT: 'SHOW_INTRO_CONTENT',
  SHOW_INTRO_SCROLL_BUTTON: 'SHOW_INTRO_SCROLL_BUTTON',
  START_REQUEST: 'START_REQUEST',
  STOP_REQUEST: 'STOP_REQUEST',
  SHOW_ERROR: 'SHOW_ERROR',
  HIDE_ERROR: 'HIDE_ERROR'
}
